/**
 * GENERATED by scripts/fetch-unit-images.mjs — re-run the script instead of
 * editing image entries by hand. Recognition photos live in public/unit-images/.
 * Licenses: US imagery is public-domain DoD photography; Iranian imagery is
 * CC BY press photography — author + license MUST be shown wherever an image
 * renders (in-game credit caption + LIVE FEEDS credits panel).
 */

export interface UnitImageInfo {
  /** filename under public/unit-images/ */
  file: string
  /** Commons file title (without the File: prefix) */
  title: string
  author: string
  license: string
  sourceUrl: string
}

export const UNIT_IMAGES: Record<string, UnitImageInfo> = {
  nimitz_cvn: { file: "nimitz_cvn.jpg", title: "USS Abraham Lincoln (CVN-72) underway during sea trials on 11 May 2017.jpg", author: "U.S. Navy photo by Mass Communication Specialist 3nd Class Juan A. Cu…", license: "Public domain", sourceUrl: "https://commons.wikimedia.org/wiki/File:USS_Abraham_Lincoln_(CVN-72)_underway_during_sea_trials_on_11_May_2017.jpg" },
  arleigh_burke: { file: "arleigh_burke.jpg", title: "US Navy 050413-N-5526M-016 The Arleigh Burke-class guided missile destroyer USS Mustin (DDG 89) underway in the Northern Persian Gulf while conducting Maritime Security Operations.jpg", author: "U.S. Navy photo by Photographer's Mate 1st Class Robert McRill", license: "Public domain", sourceUrl: "https://commons.wikimedia.org/wiki/File:US_Navy_050413-N-5526M-016_The_Arleigh_Burke-class_guided_missile_destroyer_USS_Mustin_(DDG_89)_underway_in_the_Northern_Persian_Gulf_while_conducting_Maritime_Security_Operations.jpg" },
  virginia_ssn: { file: "virginia_ssn.jpg", title: "US Navy 110909-N-OV802-222 The Virginia-class submarine Pre-Commissioning Unit (PCU) California (SSN 781) gets underway from Naval Station Norfolk.jpg", author: "U.S. Navy photo by Mass Communication Specialist 2nd Class William Ja…", license: "Public domain", sourceUrl: "https://commons.wikimedia.org/wiki/File:US_Navy_110909-N-OV802-222_The_Virginia-class_submarine_Pre-Commissioning_Unit_(PCU)_California_(SSN_781)_gets_underway_from_Naval_Station_Norfolk.jpg" },
  patriot: { file: "patriot.jpg", title: "MIM-104 Patriot surface-to-air missile system launcher.jpg", author: "Robert Barney, U.S. Air Force", license: "Public domain", sourceUrl: "https://commons.wikimedia.org/wiki/File:MIM-104_Patriot_surface-to-air_missile_system_launcher.jpg" },
  thaad: { file: "thaad.jpg", title: "THAAD missile launch in 2005 -2.jpg", author: "National Missile Defense image", license: "Public domain", sourceUrl: "https://commons.wikimedia.org/wiki/File:THAAD_missile_launch_in_2005_-2.jpg" },
  e3_sentry: { file: "e3_sentry.jpg", title: "Boeing E-3 Sentry 090512-F-7550B-902.jpg", author: "U.S. Air Force photo by 1st. Lt. Kinder Blacke", license: "Public domain", sourceUrl: "https://commons.wikimedia.org/wiki/File:Boeing_E-3_Sentry_090512-F-7550B-902.jpg" },
  us_airbase: { file: "us_airbase.jpg", title: "Al Udeid Air Base.jpg", author: "US gov", license: "Public domain", sourceUrl: "https://commons.wikimedia.org/wiki/File:Al_Udeid_Air_Base.jpg" },
  nsa_bahrain: { file: "nsa_bahrain.jpg", title: "Navy Day at Naval Support Activity Bahrain 140416-N-RJ323-385.jpg", author: "Mass Communication Specialist Petty Officer 1st Class Stephen Murphy…", license: "Public domain", sourceUrl: "https://commons.wikimedia.org/wiki/File:Navy_Day_at_Naval_Support_Activity_Bahrain_140416-N-RJ323-385.jpg" },
  s300pmu2: { file: "s300pmu2.jpg", title: "S-300 Tehran 2017.jpg", author: "Tasnim News Agency", license: "CC BY 4.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:S-300_Tehran_2017.jpg" },
  bavar373: { file: "bavar373.jpg", title: "Bavar-373 upgrade ceremony (23).jpg", author: "M. Hasan Zarifmanesh", license: "CC BY 4.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:Bavar-373_upgrade_ceremony_(23).jpg" },
  khordad3: { file: "khordad3.jpg", title: "3rd Khordad TELAR w Taer-2 missiles.jpg", author: "Meghdad Madadi", license: "CC BY 4.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:3rd_Khordad_TELAR_w_Taer-2_missiles.jpg" },
  tor_m1: { file: "tor_m1.jpg", title: "Tor M1.jpg", author: "Meghdad Madadi", license: "CC BY 4.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:Tor_M1.jpg" },
  shahab3: { file: "shahab3.jpg", title: "Shahab missile launch photographed by Satyar Emami.jpg", author: "Satyar Emami", license: "CC BY 4.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:Shahab_missile_launch_photographed_by_Satyar_Emami.jpg" },
  sejjil2: { file: "sejjil2.jpg", title: "Sejjil missile launch - November 2008 (09).jpg", author: "Vahid Reza Alaei", license: "CC BY 4.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:Sejjil_missile_launch_-_November_2008_(09).jpg" },
  fateh110: { file: "fateh110.jpg", title: "Firing Fateh-110 belong to AFAGIR.jpg", author: "Hosein Velayati", license: "CC BY 4.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:Firing_Fateh-110_belong_to_AFAGIR.jpg" },
  zolfaghar: { file: "zolfaghar.jpg", title: "Two IRGC AF Missiles.jpg", author: "M. Sadegh Nikgostar", license: "CC BY 4.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:Two_IRGC_AF_Missiles.jpg" },
  soumar: { file: "soumar.jpg", title: "Unveiling ceremony of Soumar cruise missile and other missiles (13).jpg", author: "Mohammad Agah", license: "CC BY 4.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:Unveiling_ceremony_of_Soumar_cruise_missile_and_other_missiles_(13).jpg" },
  ghadir_sub: { file: "ghadir_sub.jpg", title: "2012 Bandar Abbas new equipment induction ceremony - Ghadir-class submarine (10).jpg", author: "Ebrahim Noroozi", license: "CC BY 4.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:2012_Bandar_Abbas_new_equipment_induction_ceremony_-_Ghadir-class_submarine_(10).jpg" },
  noor_coastal: { file: "noor_coastal.jpg", title: "شلیک موشک کروز نور توسط یگان ساحلی نداجا از سواحل مکران (1).jpg", author: "عرفان کوچاری (Erfan Kouchari)", license: "CC BY 4.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:%D8%B4%D9%84%DB%8C%DA%A9_%D9%85%D9%88%D8%B4%DA%A9_%DA%A9%D8%B1%D9%88%D8%B2_%D9%86%D9%88%D8%B1_%D8%AA%D9%88%D8%B3%D8%B7_%DB%8C%DA%AF%D8%A7%D9%86_%D8%B3%D8%A7%D8%AD%D9%84%DB%8C_%D9%86%D8%AF%D8%A7%D8%AC%D8%A7_%D8%A7%D8%B2_%D8%B3%D9%88%D8%A7%D8%AD%D9%84_%D9%85%DA%A9%D8%B1%D8%A7%D9%86_(1).jpg" },
  irgc_fac: { file: "irgc_fac.jpg", title: "Commissioning ceremony of IRGC naval vessels in March 2023 (10).jpg", author: "Hossein Ghanbari", license: "CC BY 4.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:Commissioning_ceremony_of_IRGC_naval_vessels_in_March_2023_(10).jpg" },
  iran_airbase: { file: "iran_airbase.jpg", title: "F-14 Tomcat at Mehrabad preparing for Iranian Army Day 2013 (1).jpg", author: "Mohammad Shaltouki", license: "CC BY 4.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:F-14_Tomcat_at_Mehrabad_preparing_for_Iranian_Army_Day_2013_(1).jpg" },
  shahed136: { file: "shahed136.jpg", title: "Military equipment displayed for the 44th Iranian revolution anniversary rally - Shahed 136.jpg", author: "Meghdad Madadi", license: "CC BY 4.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:Military_equipment_displayed_for_the_44th_Iranian_revolution_anniversary_rally_-_Shahed_136.jpg" },
}

const US_AIRBASE_HINTS = ['udeid', 'dhafra', 'prince sultan', 'al salem', 'incirlik', 'diego garcia']

/**
 * Best-effort class match from unit name/category. May return a key with no
 * UNIT_IMAGES entry (download dropped) — callers must check the map.
 */
export function unitImageKey(unit: { name: string; category: string }): string | null {
  const n = unit.name.toLowerCase()
  if (unit.category === 'carrier_group' || n.includes('cvn')) return 'nimitz_cvn'
  if (n.includes('ddg') || n.includes('arleigh')) return 'arleigh_burke'
  if (n.includes('ssn')) return 'virginia_ssn'
  if (n.includes('patriot')) return 'patriot'
  if (n.includes('thaad')) return 'thaad'
  if (n.includes('e-3') || n.includes('awacs')) return 'e3_sentry'
  if (n.includes('nsa bahrain') || n.includes('5th fleet')) return 'nsa_bahrain'
  if (n.includes('s-300')) return 's300pmu2'
  if (n.includes('bavar')) return 'bavar373'
  if (n.includes('khordad')) return 'khordad3'
  if (n.includes('tor-m1')) return 'tor_m1'
  if (n.includes('shahab')) return 'shahab3'
  if (n.includes('sejjil')) return 'sejjil2'
  if (n.includes('fateh')) return 'fateh110'
  if (n.includes('zolfaghar')) return 'zolfaghar'
  if (n.includes('soumar')) return 'soumar'
  if (n.includes('ghadir')) return 'ghadir_sub'
  if (n.includes('coastal') || n.includes('qeshm')) return 'noor_coastal'
  if (/\bfac\b/.test(n)) return 'irgc_fac'
  if (n.includes('shahed')) return 'shahed136'
  if (unit.category === 'airbase') {
    return US_AIRBASE_HINTS.some((h) => n.includes(h)) ? 'us_airbase' : 'iran_airbase'
  }
  return null
}
